### ISSUE TITLE
constructor Sprite(scene) does not add the sprite to the scene

### ISSUE THREAD

**Issue by staudt** [quick-developers/quick#59]
Creating a new sprite with the scene on the constructor (i.e. mySprite = new Sprite(myScene);) will set the scene for the Sprite, but will not add it to it. You still have to call myScene.add(mySprite) to see it.

Is it supposed to be like this or is it a bug?

**Comment by diogoschneider** [comment]
Thanks for the report. It's not a bug, that's the intended behavior per the current API.

Long story short, (there's a lot of background to this design choice) the option to pass the parent scene as a parameter to the sprite constructor came as an alternative to needing both constructor and initialization methods in sprites, e.g.
```
class Player {
  constructor() {
    super();
    this.setColor(Color.Blue)
      .setSize(32, 32);
  }

  init() {
    this.setBoundary(this.scene); // the parent scene was unknown prior to initialization
  }
}
```
That being said, the current best practice is to always use initialization for scenes and construction with reference to the parent scene for sprites. Other than the example above, it can also avoid trouble when doing things like positioning sprites in relation to each other from the scene when the sprites also use the scene as a reference for their initial position.

**Comment by staudt** [comment]
Got it. Thanks
